#!/bin/bash
#Projector mirror with arbitrary resolution from $1
#waits indefinitely until a ctrl+c to revert back to normal

MONITOR="eDP1"
PROJECTOR="DP1"

trap "xrandr --output $MONITOR --auto; xrandr --output $PROJECTOR --auto"  SIGINT
xrandr --output $MONITOR --mode $1 --output $PROJECTOR --mode $1 --same-as $MONITOR
#xrandr --output DP1 --mode 1024x768 --right-of eDP1
tail -f /dev/null
